version: "3.7"

# nginx with bind mount to index/
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./index:/usr/share/nginx/html
      - ./index/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - messageboard

  messageboard:
    build:
      context: ./backends/message-board
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - GIN_MODE=release
