version: "3.7"

# nginx with bind mount to index/
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./index:/usr/share/nginx/html
      - ./index/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api-example
      - messageboard

  # Generic API backend for fetch example and other API needs
  api-example:
    build:
      context: ./backends/api-example
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - GIN_MODE=release
    volumes:
      - ./pkg:/app/pkg
    networks:
      - gofe-network

  # Message board backend (legacy)
  messageboard:
    build:
      context: ./backends/message-board
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      - GIN_MODE=release
    networks:
      - gofe-network

networks:
  gofe-network:
    driver: bridge
