// Code generated by qtc from "appTmpl.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line appTmpl.qtpl:1
package app

//line appTmpl.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line appTmpl.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line appTmpl.qtpl:1
func StreamAppTemplate(qw422016 *qt422016.Writer, name string, children []string) {
//line appTmpl.qtpl:1
	qw422016.N().S(`
	<h4 class="bg-red-100">Hello, `)
//line appTmpl.qtpl:2
	qw422016.E().S(name)
//line appTmpl.qtpl:2
	qw422016.N().S(`!</h4>
  <div class="flex flex-col gap-3 border">
    `)
//line appTmpl.qtpl:4
	for _, child := range children {
//line appTmpl.qtpl:4
		qw422016.N().S(`
      `)
//line appTmpl.qtpl:5
		qw422016.N().S(child)
//line appTmpl.qtpl:5
		qw422016.N().S(`
    `)
//line appTmpl.qtpl:6
	}
//line appTmpl.qtpl:6
	qw422016.N().S(`
  </div>
`)
//line appTmpl.qtpl:8
}

//line appTmpl.qtpl:8
func WriteAppTemplate(qq422016 qtio422016.Writer, name string, children []string) {
//line appTmpl.qtpl:8
	qw422016 := qt422016.AcquireWriter(qq422016)
//line appTmpl.qtpl:8
	StreamAppTemplate(qw422016, name, children)
//line appTmpl.qtpl:8
	qt422016.ReleaseWriter(qw422016)
//line appTmpl.qtpl:8
}

//line appTmpl.qtpl:8
func AppTemplate(name string, children []string) string {
//line appTmpl.qtpl:8
	qb422016 := qt422016.AcquireByteBuffer()
//line appTmpl.qtpl:8
	WriteAppTemplate(qb422016, name, children)
//line appTmpl.qtpl:8
	qs422016 := string(qb422016.B)
//line appTmpl.qtpl:8
	qt422016.ReleaseByteBuffer(qb422016)
//line appTmpl.qtpl:8
	return qs422016
//line appTmpl.qtpl:8
}
